modLoader = "javafml"
loaderVersion = "[33,)"
issueTrackerURL = "https://github.com/shedaniel/RoughlyEnoughItems/issues"
logoFile = "icon.png"
authors = "shedaniel"
license = "MIT"

[[mods]]
modId = "roughlyenoughitems"
version = "${version}"
displayName = "Roughly Enough Items (REI)"
description = '''
To allow players to view items and recipes.
'''

[[dependencies.roughlyenoughitems]]
modId = "architectury"
mandatory = true
versionRange = "[1.10.139,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughitems]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.12,)"
ordering = "NONE"
side = "BOTH"
