modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/shedaniel/RoughlyEnoughItems/issues"
logoFile = "icon.png"
authors = "shedaniel"
license = "MIT"

[[mods]]
modId = "roughlyenoughitems"
version = "${version}"
displayName = "Roughly Enough Items (REI)"
description = '''
To allow players to view items and recipes.
'''

[[dependencies.roughlyenoughitems]]
modId = "architectury"
mandatory = true
versionRange = "[4.5.75,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughitems]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.0,)"
ordering = "NONE"
side = "BOTH"
