modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/shedaniel/RoughlyEnoughItems/issues"
logoFile = "icon.png"
authors = "shedaniel"
license = "MIT"

[[mods]]
modId = "rei_plugin_compatibilities"
version = "${version}"
displayName = "REI Plugin Compatibilities"
description = '''
This is an external REI module to add support for JEI plugins.
'''

[[dependencies.rei_plugin_compatibilities]]
modId = "roughlyenoughitems"
mandatory = true
versionRange = "[7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rei_plugin_compatibilities]]
modId = "forge"
mandatory = true
versionRange = "[41.0.64,)"
ordering = "NONE"
side = "BOTH"
