modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/shedaniel/RoughlyEnoughItems/issues"
logoFile = "icon.png"
authors = "shedaniel"
license = "MIT"

[[mods]]
modId = "roughlyenoughitems"
version = "${version}"
displayName = "Roughly Enough Items (REI)"
description = '''
To allow players to view items and recipes.
'''

[[dependencies.roughlyenoughitems]]
modId = "architectury"
type = "required"
versionRange = "[8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughitems]]
modId = "cloth_config"
type = "required"
versionRange = "[10.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughitems]]
modId = "neoforge"
type = "required"
versionRange = "[20.2.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "rei.mixins.json"
